### ISSUE TITLE
bug: usage with Nuxt 3 in combination with static site generation

### ISSUE THREAD

**Issue by ahoek** [paul-thebaud/v-phone-input#24]
## Expected Behavior

The component works the same as the non--static-site generated variant

## Actual Behavior

The component works correctly in dev mode. When I generate the static site, I'll get the error:
```
ERROR  Unknown file extension ".css" for /xxx/node_modules/.pnpm/vuetify@3.5.1_typescript@5.3.3_vite-plugin-vuetify@2.0.1_vue@3.4.5/node_modules/vuetify/lib/components/VCode/VCode.css
```
If I add 'v-phone-input' to the "build.transpile" array, the site generates without issue, but I get another error when running via dev :
```
SyntaxError: The requested module '/_nuxt/@fs/xxx/node_modules/.pnpm/country-telephone-data@0.6.3/node_modules/country-telephone-data/country_telephone_data.js?v=55c67d9c' does not provide an export named 'allCountries' (at v-phone-input.js?v=55c67d9c:3:10)
```

I don't know if this is an error in the component, or in my configuration

## Steps to Reproduce the Problem

See the behavior above.

## Specifications

  - OS: MacOS
  - Browser: Chrome
  - Browser version: Version 120.0.6099.234 (Official Build) (arm64)
  - Package version: 4.1.1
  - Vuetify version: 3.5.1

**Comment by paul-thebaud** [comment]
Hello @ahoek, I'm not using nuxt at all. The first CSS error looks related to Vuetify, not VPhoneInput.
For the second one, `country-telephone-data` is a package used by VPhoneInput, but just like other external packages, it is [marked external in the lib build](https://github.com/paul-thebaud/v-phone-input/blob/ba4a8af62ee8f972f3c39e026c915e4e0e69f5e9/vite.lib.config.ts#L20-L26).
I'm sorry, but I don't know how I can help here. Do you still have an error if you _just_ remove VPhoneInput usage?

**Comment by ahoek** [comment]
Thank you for your quick answer. Both errors do not appear when I'm not using the VPhoneInput component. I'll check further and let it know when I found a solution.

**Comment by RobertoRGlyde** [comment]
I solve with `vite: {
  ...
    optimizeDeps: {
      include: ["v-phone-input > v-phone-input"],
    },
  },`

**Comment by AndreyYolkin** [comment]
You can add dependency in `transpile`

in `nuxt.config.ts`

``` ts
export default defineNuxtConfig({
  ...
  build: {
    transpile: ['v-phone-input']
  }
  ...
})
```

It should also dedupe vue and reduce bundle size

**Comment by paul-thebaud** [comment]
Looks like I got some work to do on this if Vue code is duplicated in the package export. Tagging this as a bug.

**Comment by paul-thebaud** [comment]
After investigating, looks like Vue should correctly be excluded from lib build, thanks to the [current lib build configuration](https://github.com/paul-thebaud/v-phone-input/blob/d4159557b63e4a0e77d7f80c7584f68ae2fbd320/vite.lib.config.ts#L20-L27).

**Comment by pperzyna** [comment]
I can confirm, that the issue exists.

**Comment by paul-thebaud** [comment]
I'm back. I released `v4.2.0-alpha.0` as a `next` tagged release.
Could someone else try it please?

```shell
npm install v-phone-input@next
```

If everythings good, I will release stable `v4.2.0`.

After investigation, this issue had two causes:

- `v-phone-input` should be transpiled when using Nuxt (as stated by https://github.com/paul-thebaud/v-phone-input/issues/24#issuecomment-1969762412). I added a [guide about Nuxt setup in the README](https://github.com/paul-thebaud/v-phone-input/tree/next?tab=readme-ov-file#nuxt-setup)
- Previously used [`country-telephone-data`](https://www.npmjs.com/package/country-telephone-data) looks incompatible with Nuxt, so I replaced it with [`countries-list`](https://www.npmjs.com/package/countries-list), which is maintained and give me more flexibility. In addition, countries data are included in the build (instead of being excluded)

You can also try out VPhoneInput+Nuxt inside [this Stackblitz playground](https://stackblitz.com/edit/v-phone-input-nuxt?file=app.vue,package.json).

**Comment by paul-thebaud** [comment]
Closing as it should be fixed in `v4.2.0`. Feel free to open a new issue if you still have problems with Nuxt integration.

**Comment by albertolina** [comment]
Hey Paul, still having issues with nuxt 3. When I run in dev mode it throws this error: 

`Unknown file extension ".css" for ..../web-1/website/node_modules/vuetify/lib/components/VCode/VCode.css.`

My setup

In nuxt.config.ts

`build: {
    transpile: ['v-phone-input'],
  },`
  
My plugin v-phone.client.ts

`import 'flag-icons/css/flag-icons.min.css';
import 'v-phone-input/dist/v-phone-input.css';
// @ts-ignore
import { createVPhoneInput } from 'v-phone-input';

export default defineNuxtPlugin((nuxtApp) => {
  const vPhoneInput = createVPhoneInput({
    label: 'Your phone number',
    countryIconMode: 'svg',
  });
  nuxtApp.vueApp.use(vPhoneInput);
});
`

My page.vue

`<v-phone-input label="Your Phone number" />`


 Any help?
 
 Thanks

**Comment by paul-thebaud** [comment]
Hi @albertolina, you should add `vuetify` to your transpiled dependencies 😉

**Comment by albertolina** [comment]
Hello Paul, the read me doesn't mention it. You mean like this?

` 
build: {
    transpile: ['v-phone-input', 'vuetify'],
  },
`

Still doesn't work.

**Comment by paul-thebaud** [comment]
Hi, I'll add it to the readme when I got more time. Looks weird, this was working fine in the [nuxt stackblitz playground](https://stackblitz.com/edit/v-phone-input-nuxt?file=README.md).
